version: '3'

services:
  db:
    image: postgres:13  
    volumes:
      - postgres-data:/var/lib/postgresql/data  
    ports:
      - "5432:5432"
    env_file:
      - .env
    
volumes:
  postgres-data: